import type { Currency } from "./currencies";

/** رمزارزهای پشتیبانی‌شده — قیمت IRR و USD از TGJU */
export const CRYPTO_ITEMS: Currency[] = [
  {
    code: "BTC",
    nameFa: "بیت‌کوین",
    nameEn: "Bitcoin",
    countryFa: "رمزارز",
    flag: "₿",
    tgjuKey: "crypto-bitcoin-irr",
    tgjuUsdKey: "crypto-bitcoin",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
    decimalsUsd: 2,
    kind: "crypto",
  },
  {
    code: "ETH",
    nameFa: "اتریوم",
    nameEn: "Ethereum",
    countryFa: "رمزارز",
    flag: "Ξ",
    tgjuKey: "crypto-ethereum-irr",
    tgjuUsdKey: "crypto-ethereum",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
    decimalsUsd: 2,
    kind: "crypto",
  },
  {
    code: "USDT",
    nameFa: "تتر",
    nameEn: "Tether",
    countryFa: "رمزارز",
    flag: "₮",
    tgjuKey: "crypto-tether-irr",
    tgjuUsdKey: "crypto-tether",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
    decimalsUsd: 4,
    kind: "crypto",
  },
  {
    code: "TON",
    nameFa: "گرام (تون)",
    nameEn: "Toncoin",
    countryFa: "رمزارز",
    flag: "💎",
    tgjuKey: "crypto-toncoin-irr",
    tgjuUsdKey: "crypto-toncoin",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
    decimalsUsd: 4,
    kind: "crypto",
  },
];
