export type Currency = {
  code: string;
  nameFa: string;
  nameEn: string;
  countryFa: string;
  tgjuKey: string;
  bonbastKey?: string;
  /** How many foreign units the listed price refers to (e.g. 100 for JPY). */
  quoteUnit: number;
  quoteUnitLabel?: string;
  featured: boolean;
  decimals: number;
};

export const TOMAN: Currency = {
  code: "IRT",
  nameFa: "تومان ایران",
  nameEn: "Iranian Toman",
  countryFa: "ایران",
  tgjuKey: "",
  quoteUnit: 1,
  featured: false,
  decimals: 0,
};

export const CURRENCIES: Currency[] = [
  {
    code: "USD",
    nameFa: "دلار آمریکا",
    nameEn: "US Dollar",
    countryFa: "ایالات متحده",
    tgjuKey: "price_dollar_rl",
    bonbastKey: "usd",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "EUR",
    nameFa: "یورو",
    nameEn: "Euro",
    countryFa: "منطقه یورو",
    tgjuKey: "price_eur",
    bonbastKey: "eur",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "GBP",
    nameFa: "پوند انگلیس",
    nameEn: "British Pound",
    countryFa: "بریتانیا",
    tgjuKey: "price_gbp",
    bonbastKey: "gbp",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "AED",
    nameFa: "درهم امارات",
    nameEn: "UAE Dirham",
    countryFa: "امارات",
    tgjuKey: "price_aed",
    bonbastKey: "aed",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "TRY",
    nameFa: "لیر ترکیه",
    nameEn: "Turkish Lira",
    countryFa: "ترکیه",
    tgjuKey: "price_try",
    bonbastKey: "try",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "CNY",
    nameFa: "یوان چین",
    nameEn: "Chinese Yuan",
    countryFa: "چین",
    tgjuKey: "price_cny",
    bonbastKey: "cny",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "CHF",
    nameFa: "فرانک سوئیس",
    nameEn: "Swiss Franc",
    countryFa: "سوئیس",
    tgjuKey: "price_chf",
    bonbastKey: "chf",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "JPY",
    nameFa: "ین ژاپن",
    nameEn: "Japanese Yen",
    countryFa: "ژاپن",
    tgjuKey: "price_jpy",
    bonbastKey: "jpy",
    quoteUnit: 100,
    quoteUnitLabel: "هر ۱۰۰ ین",
    featured: true,
    decimals: 0,
  },
  {
    code: "USDT",
    nameFa: "تتر",
    nameEn: "Tether",
    countryFa: "دلار دیجیتال",
    tgjuKey: "crypto-tether-irr",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "CAD",
    nameFa: "دلار کانادا",
    nameEn: "Canadian Dollar",
    countryFa: "کانادا",
    tgjuKey: "price_cad",
    bonbastKey: "cad",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "AUD",
    nameFa: "دلار استرالیا",
    nameEn: "Australian Dollar",
    countryFa: "استرالیا",
    tgjuKey: "price_aud",
    bonbastKey: "aud",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "SAR",
    nameFa: "ریال سعودی",
    nameEn: "Saudi Riyal",
    countryFa: "عربستان",
    tgjuKey: "price_sar",
    bonbastKey: "sar",
    quoteUnit: 1,
    featured: true,
    decimals: 0,
  },
  {
    code: "IQD",
    nameFa: "دینار عراق",
    nameEn: "Iraqi Dinar",
    countryFa: "عراق",
    tgjuKey: "price_iqd",
    bonbastKey: "iqd",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "OMR",
    nameFa: "ریال عمان",
    nameEn: "Omani Rial",
    countryFa: "عمان",
    tgjuKey: "price_omr",
    bonbastKey: "omr",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "KWD",
    nameFa: "دینار کویت",
    nameEn: "Kuwaiti Dinar",
    countryFa: "کویت",
    tgjuKey: "price_kwd",
    bonbastKey: "kwd",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "QAR",
    nameFa: "ریال قطر",
    nameEn: "Qatari Riyal",
    countryFa: "قطر",
    tgjuKey: "price_qar",
    bonbastKey: "qar",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "BHD",
    nameFa: "دینار بحرین",
    nameEn: "Bahraini Dinar",
    countryFa: "بحرین",
    tgjuKey: "price_bhd",
    bonbastKey: "bhd",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "AFN",
    nameFa: "افغانی",
    nameEn: "Afghan Afghani",
    countryFa: "افغانستان",
    tgjuKey: "price_afn",
    bonbastKey: "afn",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "SEK",
    nameFa: "کرون سوئد",
    nameEn: "Swedish Krona",
    countryFa: "سوئد",
    tgjuKey: "price_sek",
    bonbastKey: "sek",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "NOK",
    nameFa: "کرون نروژ",
    nameEn: "Norwegian Krone",
    countryFa: "نروژ",
    tgjuKey: "price_nok",
    bonbastKey: "nok",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "DKK",
    nameFa: "کرون دانمارک",
    nameEn: "Danish Krone",
    countryFa: "دانمارک",
    tgjuKey: "price_dkk",
    bonbastKey: "dkk",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "SGD",
    nameFa: "دلار سنگاپور",
    nameEn: "Singapore Dollar",
    countryFa: "سنگاپور",
    tgjuKey: "price_sgd",
    bonbastKey: "sgd",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "NZD",
    nameFa: "دلار نیوزیلند",
    nameEn: "New Zealand Dollar",
    countryFa: "نیوزیلند",
    tgjuKey: "price_nzd",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "THB",
    nameFa: "بات تایلند",
    nameEn: "Thai Baht",
    countryFa: "تایلند",
    tgjuKey: "price_thb",
    bonbastKey: "thb",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "AZN",
    nameFa: "منات آذربایجان",
    nameEn: "Azerbaijani Manat",
    countryFa: "جمهوری آذربایجان",
    tgjuKey: "price_azn",
    bonbastKey: "azn",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "AMD",
    nameFa: "درام ارمنستان",
    nameEn: "Armenian Dram",
    countryFa: "ارمنستان",
    tgjuKey: "price_amd",
    bonbastKey: "amd",
    quoteUnit: 1,
    featured: false,
    decimals: 1,
  },
  {
    code: "GEL",
    nameFa: "لاری گرجستان",
    nameEn: "Georgian Lari",
    countryFa: "گرجستان",
    tgjuKey: "price_gel",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "RUB",
    nameFa: "روبل روسیه",
    nameEn: "Russian Ruble",
    countryFa: "روسیه",
    tgjuKey: "price_rub",
    bonbastKey: "rub",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "PKR",
    nameFa: "روپیه پاکستان",
    nameEn: "Pakistani Rupee",
    countryFa: "پاکستان",
    tgjuKey: "price_pkr",
    quoteUnit: 1,
    featured: false,
    decimals: 1,
  },
  {
    code: "MYR",
    nameFa: "رینگیت مالزی",
    nameEn: "Malaysian Ringgit",
    countryFa: "مالزی",
    tgjuKey: "price_myr",
    bonbastKey: "myr",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "INR",
    nameFa: "روپیه هند",
    nameEn: "Indian Rupee",
    countryFa: "هند",
    tgjuKey: "price_inr",
    bonbastKey: "inr",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "HKD",
    nameFa: "دلار هنگ‌کنگ",
    nameEn: "Hong Kong Dollar",
    countryFa: "هنگ‌کنگ",
    tgjuKey: "price_hkd",
    bonbastKey: "hkd",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "JOD",
    nameFa: "دینار اردن",
    nameEn: "Jordanian Dinar",
    countryFa: "اردن",
    tgjuKey: "price_jod",
    quoteUnit: 1,
    featured: false,
    decimals: 0,
  },
  {
    code: "KRW",
    nameFa: "وون کره جنوبی",
    nameEn: "South Korean Won",
    countryFa: "کره جنوبی",
    tgjuKey: "price_krw",
    quoteUnit: 1,
    featured: false,
    decimals: 1,
  },
];

export const CURRENCY_BY_CODE: Record<string, Currency> = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c]),
);

export const CONVERTIBLE: Currency[] = [TOMAN, ...CURRENCIES];

export function searchCurrencies(query: string): Currency[] {
  const q = query.trim().toLowerCase();
  if (!q) return CURRENCIES;
  const compact = q.replace(/\s+/g, "");
  return CURRENCIES.filter((c) => {
    return (
      c.code.toLowerCase().includes(compact) ||
      c.nameFa.includes(q) ||
      c.nameEn.toLowerCase().includes(q) ||
      c.countryFa.includes(q)
    );
  });
}
