/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as CurrenciesRouteImport } from './routes/currencies'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as CurrenciesIndexRouteImport } from './routes/currencies.index'
import { Route as CurrenciesCodeRouteImport } from './routes/currencies.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesRoute = CurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesIndexRoute = CurrenciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CurrenciesRoute,
} as any)
const CurrenciesCodeRoute = CurrenciesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CurrenciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/currencies': typeof CurrenciesRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/currencies/$code': typeof CurrenciesCodeRoute
  '/currencies/': typeof CurrenciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/watchlist': typeof WatchlistRoute
  '/currencies/$code': typeof CurrenciesCodeRoute
  '/currencies': typeof CurrenciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/currencies': typeof CurrenciesRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/currencies/$code': typeof CurrenciesCodeRoute
  '/currencies/': typeof CurrenciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convert'
    | '/currencies'
    | '/watchlist'
    | '/currencies/$code'
    | '/currencies/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convert' | '/watchlist' | '/currencies/$code' | '/currencies'
  id:
    | '__root__'
    | '/'
    | '/convert'
    | '/currencies'
    | '/watchlist'
    | '/currencies/$code'
    | '/currencies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertRoute: typeof ConvertRoute
  CurrenciesRoute: typeof CurrenciesRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies': {
      id: '/currencies'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof CurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/': {
      id: '/currencies/'
      path: '/'
      fullPath: '/currencies/'
      preLoaderRoute: typeof CurrenciesIndexRouteImport
      parentRoute: typeof CurrenciesRoute
    }
    '/currencies/$code': {
      id: '/currencies/$code'
      path: '/$code'
      fullPath: '/currencies/$code'
      preLoaderRoute: typeof CurrenciesCodeRouteImport
      parentRoute: typeof CurrenciesRoute
    }
  }
}

interface CurrenciesRouteChildren {
  CurrenciesCodeRoute: typeof CurrenciesCodeRoute
  CurrenciesIndexRoute: typeof CurrenciesIndexRoute
}

const CurrenciesRouteChildren: CurrenciesRouteChildren = {
  CurrenciesCodeRoute: CurrenciesCodeRoute,
  CurrenciesIndexRoute: CurrenciesIndexRoute,
}

const CurrenciesRouteWithChildren = CurrenciesRoute._addFileChildren(
  CurrenciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertRoute: ConvertRoute,
  CurrenciesRoute: CurrenciesRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
